name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read

env:
  # it should be the tag name without the v prefix
  ARTIFACT_NAME: ${{ github.ref_name }}

jobs:
  export-google-ads-api-version:
    uses: ./.github/workflows/export-google-ads-api-version.yml
    with:
      environment: production

  build:
    name: Build
    needs: export-google-ads-api-version
    uses: ./.github/workflows/template.yml
    with:
      google-ads-api-version: ${{ needs.export-google-ads-api-version.outputs.google-ads-api-version }}
      test: false
      artifact-name: ${{ env.ARTIFACT_NAME }}
      import-suffix: .js

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    steps:
      - uses: actions/checkout@v5

      - name: Download build artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        run: |
          npm version ${GITHUB_REF#refs/tags/v} --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')

  cleanup:
    name: Cleanup
    needs: publish
    uses: ./.github/workflows/cleanup.yml
    with:
      environment: production
